services:
  franken:
    build: .
    ports:
      - "8080:80"
      - "4443:443"
      - "4443:443/udp"
    volumes:
      - ./:/app
      - caddy_data:/data
    environment:
      CADDY_GLOBAL_OPTIONS: debug
      SERVER_NAME: :80
    networks:
      - app
    tty: true
    extra_hosts:
      - host.docker.internal:10.42.203.135


  mariadb:
    image: mariadb
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb:/var/lib/mysql
    networks:
      - app

networks:
  app:
  #driver: default


volumes:
  caddy_data:
    driver: local